<a href="https://colab.research.google.com/github/AyushWaghale/ML-Practicals/blob/main/practical1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/country.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Country   34 non-null     object
 1   Age       31 non-null     float64
 2   Salary    31 non-null     float64
 3   Purchase  34 non-null     object
dtypes: float64(2), object(2)
memory usage: 1.2+ KB

In [ ]:
import numpy as np

from sklearn.impute import SimpleImputer

In [ ]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [ ]:
df = imputer.fit_transform(df)

ValueError: Cannot use mean strategy with non-numeric data:
could not convert string to float: 'India'

In [ ]:
df['Country'].unique()

array(['India', 'France', 'Germany'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
label_encoder = LabelEncoder()

In [ ]:
df_encoded = df

In [ ]:
df_encoded['Country'] = label_encoder.fit_transform(df_encoded['Country'])

In [ ]:
df_encoded['Country'].unique()

array([2, 0, 1])

In [ ]:
df_encoded['Purchase'] = label_encoder.fit_transform(df_encoded['Purchase'])

In [ ]:
df_encoded['Purchase'].unique()

array([0, 1])

In [ ]:
df_encoded

    Country   Age   Salary  Purchase
0         2  38.0  48000.0         0
1         2  38.0  48000.0         1
2         2  38.0  48000.0         0
3         2  35.0  58000.0         0
4         2  35.0  58000.0         1
5         2  35.0  58000.0         0
6         2  50.0  88000.0         0
7         2  50.0  88000.0         1
8         2  50.0  88000.0         0
9         0  43.0  45000.0         1
10        0  43.0  45000.0         0
11        0  43.0  45000.0         1
12        0  43.0  45000.0         1
13        0  48.0  65000.0         1
14        0  48.0  65000.0         0
15        0  48.0  65000.0         1
16        0  48.0  65000.0         1
17        0  49.0  79000.0         1
18        0  49.0  79000.0         0
19        0  49.0  79000.0         1
20        0  49.0  79000.0         1
21        0  37.0  77000.0         1
22        0  37.0  77000.0         0
23        0  37.0  77000.0         1
24        0  37.0  77000.0         1
25        1  30.0  54000.0         0
26        1  30.0  54000.0         1
27        1  30.0  54000.0         0
28        1  40.0      NaN         0
29        1  40.0      NaN         1
30        1  40.0      NaN         0
31        1   NaN  53000.0         0
32        1   NaN  53000.0         1
33        1   NaN  53000.0         0

In [ ]:
df_encoded = imputer.fit_transform(df_encoded)

In [ ]:
df_encoded

array([[2.00000000e+00, 3.80000000e+01, 4.80000000e+04, 0.00000000e+00],
       [2.00000000e+00, 3.80000000e+01, 4.80000000e+04, 1.00000000e+00],
       [2.00000000e+00, 3.80000000e+01, 4.80000000e+04, 0.00000000e+00],
       [2.00000000e+00, 3.50000000e+01, 5.80000000e+04, 0.00000000e+00],
       [2.00000000e+00, 3.50000000e+01, 5.80000000e+04, 1.00000000e+00],
       [2.00000000e+00, 3.50000000e+01, 5.80000000e+04, 0.00000000e+00],
       [2.00000000e+00, 5.00000000e+01, 8.80000000e+04, 0.00000000e+00],
       [2.00000000e+00, 5.00000000e+01, 8.80000000e+04, 1.00000000e+00],
       [2.00000000e+00, 5.00000000e+01, 8.80000000e+04, 0.00000000e+00],
       [0.00000000e+00, 4.30000000e+01, 4.50000000e+04, 1.00000000e+00],
       [0.00000000e+00, 4.30000000e+01, 4.50000000e+04, 0.00000000e+00],
       [0.00000000e+00, 4.30000000e+01, 4.50000000e+04, 1.00000000e+00],
       [0.00000000e+00, 4.30000000e+01, 4.50000000e+04, 1.00000000e+00],
       [0.00000000e+00, 4.80000000e+01, 6.50000000e+04, 1.00000000e+00],
       [0.00000000e+00, 4.80000000e+01, 6.50000000e+04, 0.00000000e+00],
       [0.00000000e+00, 4.80000000e+01, 6.50000000e+04, 1.00000000e+00],
       [0.00000000e+00, 4.80000000e+01, 6.50000000e+04, 1.00000000e+00],
       [0.00000000e+00, 4.90000000e+01, 7.90000000e+04, 1.00000000e+00],
       [0.00000000e+00, 4.90000000e+01, 7.90000000e+04, 0.00000000e+00],
       [0.00000000e+00, 4.90000000e+01, 7.90000000e+04, 1.00000000e+00],
       [0.00000000e+00, 4.90000000e+01, 7.90000000e+04, 1.00000000e+00],
       [0.00000000e+00, 3.70000000e+01, 7.70000000e+04, 1.00000000e+00],
       [0.00000000e+00, 3.70000000e+01, 7.70000000e+04, 0.00000000e+00],
       [0.00000000e+00, 3.70000000e+01, 7.70000000e+04, 1.00000000e+00],
       [0.00000000e+00, 3.70000000e+01, 7.70000000e+04, 1.00000000e+00],
       [1.00000000e+00, 3.00000000e+01, 5.40000000e+04, 0.00000000e+00],
       [1.00000000e+00, 3.00000000e+01, 5.40000000e+04, 1.00000000e+00],
       [1.00000000e+00, 3.00000000e+01, 5.40000000e+04, 0.00000000e+00],
       [1.00000000e+00, 4.00000000e+01, 6.34516129e+04, 0.00000000e+00],
       [1.00000000e+00, 4.00000000e+01, 6.34516129e+04, 1.00000000e+00],
       [1.00000000e+00, 4.00000000e+01, 6.34516129e+04, 0.00000000e+00],
       [1.00000000e+00, 4.15161290e+01, 5.30000000e+04, 0.00000000e+00],
       [1.00000000e+00, 4.15161290e+01, 5.30000000e+04, 1.00000000e+00],
       [1.00000000e+00, 4.15161290e+01, 5.30000000e+04, 0.00000000e+00]])

In [ ]:
df_encoded = pd.DataFrame(df_encoded)

In [ ]:
df_encoded.isnull().sum()

0    0
1    0
2    0
3    0
dtype: int64

In [ ]:
df_encoded.describe()

               0          1             2          3
count  34.000000  34.000000     34.000000  34.000000
mean    0.794118  41.516129  63451.612903   0.529412
std     0.844928   6.198098  13796.878676   0.506640
min     0.000000  30.000000  45000.000000   0.000000
25%     0.000000  37.000000  53000.000000   0.000000
50%     1.000000  41.516129  63451.612903   1.000000
75%     1.750000  48.000000  77000.000000   1.000000
max     2.000000  50.000000  88000.000000   1.000000

In [ ]:
x = df_encoded.iloc[:,0:3]
y = df_encoded.iloc[:,-1]

In [ ]:
y.shape,x.shape

((34,), (34, 3))

Min Max Scalaer

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler = MinMaxScaler()

In [ ]:
x_scale = pd.DataFrame(scaler.fit_transform(x))

In [ ]:
x_scale

      0         1         2
0   1.0  0.400000  0.069767
1   1.0  0.400000  0.069767
2   1.0  0.400000  0.069767
3   1.0  0.250000  0.302326
4   1.0  0.250000  0.302326
5   1.0  0.250000  0.302326
6   1.0  1.000000  1.000000
7   1.0  1.000000  1.000000
8   1.0  1.000000  1.000000
9   0.0  0.650000  0.000000
10  0.0  0.650000  0.000000
11  0.0  0.650000  0.000000
12  0.0  0.650000  0.000000
13  0.0  0.900000  0.465116
14  0.0  0.900000  0.465116
15  0.0  0.900000  0.465116
16  0.0  0.900000  0.465116
17  0.0  0.950000  0.790698
18  0.0  0.950000  0.790698
19  0.0  0.950000  0.790698
20  0.0  0.950000  0.790698
21  0.0  0.350000  0.744186
22  0.0  0.350000  0.744186
23  0.0  0.350000  0.744186
24  0.0  0.350000  0.744186
25  0.5  0.000000  0.209302
26  0.5  0.000000  0.209302
27  0.5  0.000000  0.209302
28  0.5  0.500000  0.429107
29  0.5  0.500000  0.429107
30  0.5  0.500000  0.429107
31  0.5  0.575806  0.186047
32  0.5  0.575806  0.186047
33  0.5  0.575806  0.186047

In [ ]:
x.describe(),x_scale.describe()

(               0          1             2
 count  34.000000  34.000000     34.000000
 mean    0.794118  41.516129  63451.612903
 std     0.844928   6.198098  13796.878676
 min     0.000000  30.000000  45000.000000
 25%     0.000000  37.000000  53000.000000
 50%     1.000000  41.516129  63451.612903
 75%     1.750000  48.000000  77000.000000
 max     2.000000  50.000000  88000.000000,
                0          1          2
 count  34.000000  34.000000  34.000000
 mean    0.397059   0.575806   0.429107
 std     0.422464   0.309905   0.320858
 min     0.000000   0.000000   0.000000
 25%     0.000000   0.350000   0.186047
 50%     0.500000   0.575806   0.429107
 75%     0.875000   0.900000   0.744186
 max     1.000000   1.000000   1.000000)

StandardScalar

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
std_scaler = StandardScaler()

In [ ]:
pd.DataFrame(std_scaler.fit_transform(x))

           0         1             2
0   1.448664 -0.575823 -1.136777e+00
1   1.448664 -0.575823 -1.136777e+00
2   1.448664 -0.575823 -1.136777e+00
3   1.448664 -1.067121 -4.010760e-01
4   1.448664 -1.067121 -4.010760e-01
5   1.448664 -1.067121 -4.010760e-01
6   1.448664  1.389371  1.806029e+00
7   1.448664  1.389371  1.806029e+00
8   1.448664  1.389371  1.806029e+00
9  -0.953998  0.243008 -1.357488e+00
10 -0.953998  0.243008 -1.357488e+00
11 -0.953998  0.243008 -1.357488e+00
12 -0.953998  0.243008 -1.357488e+00
13 -0.953998  1.061838  1.139151e-01
14 -0.953998  1.061838  1.139151e-01
15 -0.953998  1.061838  1.139151e-01
16 -0.953998  1.061838  1.139151e-01
17 -0.953998  1.225604  1.143897e+00
18 -0.953998  1.225604  1.143897e+00
19 -0.953998  1.225604  1.143897e+00
20 -0.953998  1.225604  1.143897e+00
21 -0.953998 -0.739589  9.967569e-01
22 -0.953998 -0.739589  9.967569e-01
23 -0.953998 -0.739589  9.967569e-01
24 -0.953998 -0.739589  9.967569e-01
25  0.247333 -1.885952 -6.953566e-01
26  0.247333 -1.885952 -6.953566e-01
27  0.247333 -1.885952 -6.953566e-01
28  0.247333 -0.248291 -5.352933e-16
29  0.247333 -0.248291 -5.352933e-16
30  0.247333 -0.248291 -5.352933e-16
31  0.247333  0.000000 -7.689267e-01
32  0.247333  0.000000 -7.689267e-01
33  0.247333  0.000000 -7.689267e-01

Train test Split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [ ]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((27, 3), (7, 3), (27,), (7,))